### ISSUE TITLE
Shouldn't need a new launchapp to be able to launch Photoshop CC

### ISSUE THREAD

**Issue by mathurf** [shotgunsoftware/tk-photoshopcc#63]
Without the new launchapp I can't launch Photoshop CC from Shotgun Desktop. I don't think launchapp updates should be needed to be able to launch PhotoshopCC. This could cause an issue if someone only update the Photoshop engine. Both, tk-photoshopcc engine and tk-framework-adobe will be updated/installed but launchapp will not. Here is the output from SG Desktop console
[PhotoshopCCErrorWithCurrentLaunchapp.txt](https://github.com/shotgunsoftware/tk-photoshopcc/files/2890103/PhotoshopCCErrorWithCurrentLaunchapp.txt)

**Comment by martinminsel** [comment]
I think this is resolved by the latest changes in tk-aftereffects and tk-photoshopcc as we don't rely on the launchapp any more

**Comment by manneohrstrom** [comment]
yep, i closed the PR for the launchapp. Closing!
