### ISSUE TITLE
We shouldn't have 2 Shotgun extensions in Photoshop CC

### ISSUE THREAD

**Issue by mathurf** [shotgunsoftware/tk-photoshopcc#64]
After I did update tk-photoshopcc engine to use the new tk-framework-adobe I did get 2 Shotgun extensions in Photoshop CC. Also, first time I launched Photoshop after the update it opened the old extensions which hang on loading shotgun integration. I think If the framework is being used, then it checks to see if the old extension exists and deletes it to avoid that issue. 

Steps:
- Launch Photoshop CC from Shotgun Desktop using a current tk-config-basic (no Adobe framework)
= Using current Shotgun Extensions
- Modify your project to use the updated basic config to use the new integration with Adobe framework
- Launch Photoshop CC from Shotgun Desktop
= Shotgun dialog is hang on loading shotgun integration. This is because it using the previous integration. You need to launch the other Shotgun extensions from Photoshop menu (Window --> Extensions)

Here is what it looks like in Photoshop when I have both open:

![photoshop2extensions](https://user-images.githubusercontent.com/8168836/53270554-06f44700-36ba-11e9-9f2f-527526fe9b99.png)

**Comment by manneohrstrom** [comment]
Meeting notes: This is complicated, the new code can handle the case where it detects an old plugin being used, but older projects where the old plugin is being used cannot detect the new plugin so you'll end up with two plugins. 

Let's try and see if keeping the old name and see if that works seemlessly. Francis can help with old cases. Worst case, let's rename the menu option in the new version to "shotgun panel" to make it easier to distinguish between new and old in edge cases.

**Comment by martinminsel** [comment]
Hi @mathurf ,
Please checkout the latest state of tk-framework-adobe, tk-photoshopcc and tk-aftereffects.
Now:
1. clean your ~/Libraries/Adobe/CEP/extensions directory
2. open Photoshop using the OLD tk-photoshopcc
3. open the Shotgun Panel
4. close Photoshop
5. open Photoshop using the NEW tk-photoshopcc
6. The new panel should show.

Cheers.
Martin

**Comment by manneohrstrom** [comment]
Assigning to @mathurf for QA.

**Comment by mathurf** [comment]
Looks good!
Tested same steps than above and also make sure that it is still working fine if no extension already exist.

**Comment by mathurf** [comment]
Reopening this ticket because that fix broke the backward compatibility. It means that as soon as we update the Shotgun extension by launching AFx current Photoshop CC integration (engine v1.6.3 and before) is not working anymore.

**Steps**
- Launch Photoshop CC from a project running old integration (engine v1.6.3 and before)
- Setup a new project with the new updated config for AFx integration and launch either AFx or PS CC
= Everything is working fine and Shotgun extension (com.sg.basic.ps) gets updated to version v2.0.0
- Go back to your other project running old integration and launch Photoshop CC
= Shotgun integration is broken

**Comment by mathurf** [comment]
this is now resolved in the latest tk-framework-adobe version in the app store (v1.0.1)
